name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install streamlit plotly
    
    - name: Run first smoke test
      run: |
        python train.py --seed 123 --epochs 1 --steps_per_epoch 2 --batch_size 2 --max_new_tokens 5 --profiler on
        echo "First run completed"
    
    - name: Create symlink for first run
      run: |
        # Find the most recent run directory
        LATEST_RUN=$(ls -td runs/run_* | head -1)
        echo "First run directory: $LATEST_RUN"
        # Create symlink for CI artifact naming
        ln -sf "$LATEST_RUN" runs/run_a
    
    - name: Run second smoke test
      run: |
        python train.py --seed 123 --epochs 1 --steps_per_epoch 2 --batch_size 2 --max_new_tokens 5 --profiler on
        echo "Second run completed"
    
    - name: Create symlink for second run
      run: |
        # Find the most recent run directory
        LATEST_RUN=$(ls -td runs/run_* | head -1)
        echo "Second run directory: $LATEST_RUN"
        # Create symlink for CI artifact naming
        ln -sf "$LATEST_RUN" runs/run_b
    
    - name: Update latest symlink
      run: |
        # Update the latest symlink to point to the second run
        ln -sf "$(ls -td runs/run_* | head -1)" runs/latest
    
    - name: Assert determinism
      run: |
        python scripts/assert_determinism.py --run_a runs/run_a --run_b runs/run_b --tolerance 1e-6
    
    - name: Upload first run artifacts
      uses: actions/upload-artifact@v4
      with:
        name: run_a
        path: runs/run_a/
        retention-days: 7
    
    - name: Upload second run artifacts
      uses: actions/upload-artifact@v4
      with:
        name: run_b
        path: runs/run_b/
        retention-days: 7
    
    - name: List run artifacts
      run: |
        echo "=== Run artifacts ==="
        ls -la runs/
        echo "=== First run contents ==="
        ls -la runs/run_a/
        echo "=== Second run contents ==="
        ls -la runs/run_b/
        echo "=== Latest symlink ==="
        ls -la runs/latest/
